default['ruby-env']['user']           = 'ec2-user'
default['ruby-env']['group']          = 'ec2-user'
default['ruby-env']['version']        = '2.2.2'
default['ruby-env']['rbenv_url']      = 'https://github.com/sstephenson/rbenv'
default['ruby-env']['ruby-build_url'] = 'https://github.com/sstephenson/ruby-build'
